:toc: auto
= MetaCode Code Generator

== Features

* Generates a working Spring WebMvc or Spring WebFlux application
** A project with a single controller will have about 600 lines of code and about 80 tests generated
* Generates unit and integration tests that currently provide 100% code coverage
* Assigns resource objects unique identifiers that have 160-bit entropy, the highest amount recommended by OAuth2 (160 bits is approximately 1.46 x 10^48^ possible values). 
* Supported Integrations: 
** Postges 
** TestContainers
** Liquibase

With Postgres integration, the JPA properties within `application.properties` reference Postgres JDBC drivers. With TestContainers integration, the test cases use TestContainers to emulate the database. When both Postgres and TestContainers are used, the tests use the Postgres flavor of the test container. With Liquibase, a simple configuration is generated as a starting point.

== Homebrew Install

Metacode is available on Homebrew. To install it, run these commands:

```[bash]
$ brew tap staycaffeinated/tap
$ brew install metacode
```

Metacode is compiled with Java 11 as the target JVM,
so you will need at least Java 11 to run it.


== Quick Start Guide

To demonstrate how to generate a project with MetaCode, we'll walk through generating Spring's Pet Store example,
with three endpoints: pets, owners, and stores.

=== The Spring Pet Store in Spring WebFlux 

We'll start with Spring WebFlux, which uses asynchronous communication, with Mono and Flux streams.

[sidebar]
Be aware that MetaCode creates everything in the current working directory, so create the project directory _first_, navigate into it,  _then_ run the `metacode` command.

.Step 1: Create the basic project. 
[source,bash]
----
$ mkdir petstore-webflux
$ cd petstore-webflux
$ metacode create project spring-webflux --name petstore --package acme.petstore --base-path /petstore
----

.Step 2: Create an endpoint for pets
[source,bash]
----
$ metacode create endpoint --resource Pet --route /pets 
----

.Step 3: Create a Gradle wrapper. 
[source,bash]
----
$ gradle wrapper
----

.Step 4: Compile the code
[source,bash]
----
$ ./gradlew build
----

.Step 5: Create endpoints for stores and owners.
[source,bash]
----
$ metacode create endpoint --resource Store --route /stores
$ metacode create endpoint --resource Owner --route /owners
$ ./gradlew build
----

.Step 6: Run the application again to see where things stand
[source,bash]
----
$ ./gradlew bootRun
----

Try these URLs in your browser to see what happens
[source,bash]
----
$ http localhost:8080/petstore/pets/findAll
$ http localhost:8080/petstore/stores/findAll
$ http localhost:8080/petstore/owners/findAll
$ http localhost:8080/petstore/pets
$ http localhost:8080/petstore/pets/[resourceId]
$ http localhost:8080/petstore/_internal/health
$ http localhost:8080/petstore/_internal/health/liveness
----

=== The Spring Pet Store in Spring WebMvc 

This example shows using Spring WebMvc, which uses synchronous communication.  

.Step 1: Create the basic project. 
[source,bash]
----
$ mkdir petstore-webmvc
$ cd petstore-webmvc
$ metacode create project spring-webmvc --name petstore --package acme.petstore --base-path /petstore
----

.Step 2: Create an endpoint for pets
[source,bash]
----
$ metacode create endpoint --resource Pet --route /pets 
----

.Step 3: Create a Gradle wrapper. 
[source,bash]
----
$ gradle wrapper
----

.Step 4: Compile the code
[source,bash]
----
$ ./gradlew build
----

.Step 5: Create endpoints for stores and owners.
[source,bash]
----
$ metacode create endpoint --resource Store --route /stores
$ metacode create endpoint --resource Owner --route /owners
$ ./gradlew build
----

.Step 6: Run the application again to see where things stand
[source,bash]
----
$ ./gradlew bootRun
----

Try these URLs in your browser to see what happens
[source,bash]
----
$ http localhost:8080/petstore/pets/findAll
$ http localhost:8080/petstore/stores/findAll
$ http localhost:8080/petstore/owners/findAll
$ http localhost:8080/petstore/pets
$ http localhost:8080/petstore/pets/[resourceId]
$ http localhost:8080/petstore/_internal/health
$ http localhost:8080/petstore/_internal/health/liveness
----

=== Generate a Spring Boot project

When you only want the bare minimum of code generated, the `spring-boot` template is available.
The `spring-boot` template generates an `Application.java`, some helper classes, and an
`ApplicationTests.java`.

To create such a project, following this recipe:
[source,bash]
----
$ mkdir basic-springboot
$ cd basic-springboot
$ metacode create project spring-boot --name hello-world --package acme.greeting --base-path /greeting
----

include::docs/DeepDive.adoc[]
